[project]
name = "chat-bot"
version = "0.1.0"
description = "This is local chat-gpt integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.79.0",
    "pypdf2>=3.0.1",
    "streamlit>=1.45.1",
    "PyPDF2>=3.0.1"
]
